### ISSUE TITLE
Will there be a demo ?

### ISSUE THREAD

**Issue by AboutRSS** [Importantus/RSSwipe#19]
Hi. Thanks for the creation. Just wondering if there will be a demo in the near future.

**Comment by Importantus** [comment]
Thank you for your interest. No, there will not be a public demo instance (from us) because unfortunately we do not have the necessary technical and legal resources.  

However, we have just updated our deployment process. :) 
You can now simply host a demo version (and also a production version) yourself on your PC or a server using Docker and docker-compose.

But please note, that this project is still under development and the architecture is subject to change 🏗️

---

Get the `docker-compose.yml` file in the docker directory of this repository:

```sh
wget https://raw.githubusercontent.com/Importantus/RSSwipe/main/docker/docker-compose.yml
```

Create an `.env` file in the same directory as the docker-compose file and copy the content of the `.env.prod` file into it.

```sh
wget -O .env https://raw.githubusercontent.com/Importantus/RSSwipe/main/.env.prod
```

Edit the `.env` file and set the values for the environment variables.

Start the app (this may take a short while):

```sh
docker compose up
```

The app is now running on port 80 or the custom `FRONTEND_FORWARD_PORT` you set in the `.env` file. 

To run the app in the background, add the `-d` flag:

```sh
docker compose up -d
```

To update the app, pull the latest changes from the repository and restart the app:

```sh
docker compose pull && docker compose up -d
```

**Comment by AboutRSS** [comment]
Thanks your nice explanation. Will give it a try.
